### ISSUE TITLE
Add article to Press page on site

### ISSUE THREAD

**Issue by seeglenn** [fimio-xyz/fimio-xyz.github.io#17]
Omoju, and by extension Fimio, were featured in a linkedin article today in honor of International Women's Day. We need to add it to the Fimio website! @joshuaiokua, can you add it please?

Here's the link: https://www.linkedin.com/pulse/fintech-women-you-need-know-wednesday-march-8th-empire-startups/

Please let me know what else you need to put it up!

**Comment by joshuaiokua** [comment]
Article added to new [branch](https://github.com/fimio-xyz/fimio-xyz.github.io/pull/19) which is ready for review by @omoju.

**Comment by joshuaiokua** [comment]
[Branch](https://github.com/fimio-xyz/fimio-xyz.github.io/pull/19) has been merged.
